# This is a basic workflow to help you get started with Actions

name: Buildsus

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  buildAndroid:
    name: buildWindows
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1

      - name: Setup Haxe
        uses: krdlab/setup-haxe@v1.1.5
        with:
          haxe-version: 4.2.5

      - name: Install Haxelib
        run: |
          haxelib setup C:/haxelib
          haxelib install hxcpp
          haxelib install lime 7.9.0
          haxelib install hxCodec
          haxelib install openfl 9.1.0
          haxelib --never install flixel
          haxelib run lime setup flixel
          haxelib install flixel-tools
          haxelib install flixel-ui
          haxelib install hxCodec
          haxelib install hxp
          haxelib install hscript
          haxelib install flixel-addons
          haxelib install discord_rpc
          haxelib install flxanimate
          haxelib install linc_luajit
          haxelib list

      - name: Create Version Tag
        run: echo "${{github.run_id}}" > VERSION

      - name: Setup Lime
        run: |
          haxelib set lime 7.9.0 
          haxelib set openfl 9.1.0 
          haxelib list
      - name: Compile
        run: haxelib run lime build windows --app-version="4.0.0-${{ github.run_id}}"

      - name: Publish Artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          name: Windows Build
          path: export/release/windows/bin
